name: Build

on: 
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - run: echo hi 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container
        uses: devcontainers/ci@v0.3
        with: 
          imageName: bigspaceships/base-codespace-config
