name: Update Repos

on: workflow_dispatch

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Repos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: Run Script
        run: ./devcontainer-update/update-repos.sh

